/**
 * core/project-version.js
 *
 * Single source of truth for the "AI Workflow" version badge shown in
 * the UI (see ui/app.js's version-badge rendering). Update this object
 * at the start of each new EPIC so the deployed page's badge always
 * reflects what's actually running — this is intentionally the ONLY
 * place that needs editing to bump the displayed version.
 */
export const AI_WORKFLOW_VERSION = {
  version: 'v1.6.0',
  epic: 'EPIC 2E-O',
  label: 'AI Workflow v1.6.0 (EPIC 2E-O)',
  title: 'Target-aware Color Match & Lightroom Round-trip Fidelity',
  status: 'Legacy Active · Target-aware Candidate · Lightroom Round-trip Required · Production Locked',
  statusLine: 'Legacy Active · Target-aware Candidate · Lightroom Round-trip Required · Production Locked',
  upgradedSystems: [
    'Reference Color Intelligence',
    'Photographer Intent Intelligence',
    'Intent Hierarchy & Strength',
    'Capture Capability Intelligence',
    'Style Budget Intelligence',
    'Lightroom Mapping V2 Planner',
    'Budget-to-Lightroom Translation V2',
    'Safety Clamp & Over-stack Protection V2',
    'Shadow Compare Report V2',
    'Controlled Activation Gate',
    'Legacy Safety Overlay V2',
    'Overlay Preview / Controlled Simulation',
    'Controlled Overlay Test Gate',
    'Controlled Overlay Preview Sandbox',
    'Controlled Preview Human Review',
    'Interactive Review Console',
    'Side-by-Side Data Comparison',
    'Data-level Legacy vs. V2 Analysis',
    'Isolated Visual Preview Render Plan',
    'Legacy Browser Preview Rendering',
    'Controlled V2 Browser Preview Rendering',
    'Interactive Before/After Split Viewer',
    'Controlled V2 Candidate Review Pilot',
    'Guided Candidate Cohort Intake',
    'Reference/Target Signature Schema V1',
    'Semantic Color Match Delta Foundation',
    'Core Match Shadow Inspector',
    'N2 Photographic Compensation & Object/Illuminant Separation',
    'N3 Bounded Lightroom Candidate Mapping',
    'N4 Kelvin-calibrated Browser Match Preview',
    'N4 Matched Preview Re-analysis & Fidelity Scoring',
    'N5 Local Color Match Evaluation Harness',
    'Candidate XMP In-memory Generation',
    'Target-aware High-key / Neutral White Protection',
    'Target-aware Skin Warmth / Saturation Protection',
    'Scene-object Channel Transferability Guard',
    'RAW / Rendered Lightroom Compatibility Profile',
    'Preview-to-Lightroom Round-trip Fidelity Inspector',
    'Lightroom Export Re-analysis Workflow',
    'Reference/Target Reason Trace',
    'Reference-vs-Target Evidence Quality Gate',
    'Save-and-Next Review Workflow',
    'Semantic Cohort Save Receipts',
    'Verified Pixel Cohort Analysis',
    'Candidate Safety / Regression Stop Gates',
    'Legacy-left / Controlled-V2-right Comparison',
    'One-time Display Canvas Normalization',
    'Strict Aspect-Ratio Alignment Tolerance',
    'CSS-only Interactive Slider Movement',
    'Interactive Safety-Anomaly Blocking',
    'Approximate Browser Preview (Non-Production)',
    'Rollback-ready Legacy Fallback',
    'Legacy Mapping Still Active',
    'XMP Export Unchanged',
  ],
};
